-- ============================================================================
--  REQUISITOS BASE  (ejecutar PRIMERO, una sola vez)
-- ----------------------------------------------------------------------------
--  Los 3 mapas usan una pequena "caja de herramientas" comun:
--    * GENM000.PJ            -> imprime texto largo (JSON) sin cortarlo
--    * GENM000.USUARIO_ACTUAL-> devuelve el usuario que inicio sesion
--    * una tabla de usuarios/roles minima (GEN_USUARIO / GEN_ROL / GEN_USUARIO_ROL)
--
--  SI TU APLICACION YA TIENE una tabla de usuarios y este paquete, NO ejecutes
--  este archivo: solo asegurate de que existan GENM000.PJ y GENM000.USUARIO_ACTUAL.
--  Es idempotente: se puede volver a ejecutar sin romper nada.
-- ============================================================================

-- 1) Caja de herramientas
create or replace package GENM000 as
  procedure PJ (P_CLOB clob);              -- imprime un CLOB por htp en trozos
  function  USUARIO_ACTUAL return varchar2; -- login del usuario actual (APEX)
end GENM000;
/
create or replace package body GENM000 as
  procedure PJ (P_CLOB clob) is
    l_len number := dbms_lob.getlength(P_CLOB);
    l_pos number := 1;
    l_amt number := 8000;
  begin
    while l_pos <= l_len loop
      htp.prn(dbms_lob.substr(P_CLOB, l_amt, l_pos));
      l_pos := l_pos + l_amt;
    end loop;
  end;
  function USUARIO_ACTUAL return varchar2 is
  begin
    -- en APEX, V('APP_USER') es quien inicio sesion; fuera de APEX, el usuario de BD
    return upper(nvl(v('APP_USER'), user));
  end;
end GENM000;
/

-- 2) Usuarios y roles minimos (solo si no existen)
declare
  procedure ddl(p varchar2) is
  begin execute immediate p;
  exception when others then if sqlcode not in (-955,-1430,-2260,-1442,-1451) then raise; end if; end;
begin
  ddl(q'[create table GEN_USUARIO (
    USU_CODIGO      number generated by default as identity primary key,
    USU_LOGIN       varchar2(60) unique not null,
    USU_NOMBRE      varchar2(120),
    USU_ACTIVO      varchar2(1) default 'S',
    USU_AVATAR      blob,
    USU_AVATAR_MIME varchar2(100),
    USU_COLOR       varchar2(9)
  )]');
  ddl(q'[create table GEN_ROL (
    ROL_CODIGO number generated by default as identity primary key,
    ROL_NOMBRE varchar2(60) unique not null,
    ROL_ACTIVO varchar2(1) default 'S'
  )]');
  ddl(q'[create table GEN_USUARIO_ROL (
    USRO_USU_CODIGO number not null,
    USRO_ROL_CODIGO number not null
  )]');
end;
/

-- 3) Semilla: un usuario ADMIN con rol ADMINISTRADOR (para probar el monitoreo)
declare
  l_u number; l_r number;
begin
  begin
    insert into GEN_ROL (ROL_NOMBRE) values ('ADMINISTRADOR');
  exception when dup_val_on_index then null; end;
  begin
    insert into GEN_USUARIO (USU_LOGIN, USU_NOMBRE) values ('ADMIN','Administrador');
  exception when dup_val_on_index then null; end;
  select USU_CODIGO into l_u from GEN_USUARIO where USU_LOGIN='ADMIN';
  select ROL_CODIGO into l_r from GEN_ROL where ROL_NOMBRE='ADMINISTRADOR';
  begin
    insert into GEN_USUARIO_ROL (USRO_USU_CODIGO, USRO_ROL_CODIGO) values (l_u, l_r);
  exception when others then null; end;
  commit;
end;
/
