-- ============================================================================
-- Modulo MON (Monitoreo en tiempo real): posiciones de usuarios + avatar propio.
-- Idempotente: se puede reejecutar sin romper.
-- ============================================================================

-- 1) Avatar de perfil del usuario (imagen opcional + color/inicial de respaldo).
--    Se agrega a GEN_USUARIO para reutilizarlo en todo el sistema (chat, monitoreo...).
-- NOTA: no se usan vistas USER_* para las guardas: la conexion es ADMIN con
-- current_schema=WKSP, y USER_TAB_COLUMNS/USER_TABLES van por el usuario conectado
-- (ADMIN), no por el schema actual. Por eso se atrapan las excepciones DDL.
declare
  procedure add_col(p_ddl varchar2) is
  begin
    execute immediate 'alter table GEN_USUARIO add ('||p_ddl||')';
  exception when others then
    if sqlcode not in (-1430) then raise; end if;  -- -1430: la columna ya existe
  end;
begin
  add_col('USU_AVATAR blob');
  add_col('USU_AVATAR_MIME varchar2(100)');
  add_col('USU_COLOR varchar2(9)');
end;
/
-- color por defecto estable por codigo (misma paleta que los canales de chat)
update GEN_USUARIO set USU_COLOR =
  case mod(USU_CODIGO,6) when 0 then '#4f46e5' when 1 then '#16a34a' when 2 then '#e11d48'
                         when 3 then '#f59e0b' when 4 then '#7048e8' else '#0891b2' end
 where USU_COLOR is null
/

-- 2) Posiciones reportadas (historial; la ultima por usuario alimenta el mapa).
declare
  procedure ddl(p varchar2) is
  begin
    execute immediate p;
  exception when others then
    if sqlcode not in (-955) then raise; end if;  -- -955: el objeto ya existe
  end;
begin
  ddl(q'[
    create table MON_POSICION (
      POS_CODIGO       number         generated by default as identity primary key,
      POS_USU_CODIGO   number         not null,
      POS_LAT          number         not null,
      POS_LNG          number         not null,
      POS_PRECISION_M  number,
      POS_VELOCIDAD_MS number,          -- m/s (de la API o calculada)
      POS_RUMBO        number,          -- grados 0..360 (opcional)
      POS_BATERIA      number,          -- 0..100 (opcional)
      POS_FECHA        timestamp      default systimestamp not null,
      constraint MON_POSICION_FK foreign key (POS_USU_CODIGO)
                 references GEN_USUARIO (USU_CODIGO) on delete cascade
    )]');
  ddl('create index MON_POSICION_IX on MON_POSICION (POS_USU_CODIGO, POS_FECHA desc)');
end;
/
commit
/
