-- ============================================================================
-- MON - Reglas de alerta y bitacora de alertas disparadas.
-- Idempotente (atrapa -955/-1430; ver nota en c0_mon_tablas.sql sobre USER_*).
-- ============================================================================
declare
  procedure ddl(p varchar2) is
  begin
    execute immediate p;
  exception when others then
    if sqlcode not in (-955,-1430) then raise; end if;
  end;
begin
  -- Regla: que evento vigilar.
  --   REG_TIPO: 'VELOCIDAD' (supera REG_UMBRAL_KMH)
  --             'LLEGADA'   (entra al circulo REG_LAT/LNG + REG_RADIO_M)
  --             'SALIDA'    (sale del circulo)
  --   REG_USU_OBJETIVO: usuario a vigilar (null = todos los que comparten)
  ddl(q'[
    create table MON_REGLA (
      REG_CODIGO       number generated by default as identity primary key,
      REG_NOMBRE       varchar2(120) not null,
      REG_TIPO         varchar2(12)  not null,
      REG_UMBRAL_KMH   number,
      REG_LAT          number,
      REG_LNG          number,
      REG_RADIO_M      number,
      REG_USU_OBJETIVO number,
      REG_ACTIVO       varchar2(1) default 'S' not null,
      REG_USUARIO_CREA varchar2(60),
      REG_FECHA_CREA   timestamp default systimestamp,
      constraint MON_REGLA_TIPO_CK check (REG_TIPO in ('VELOCIDAD','LLEGADA','SALIDA')),
      constraint MON_REGLA_OBJ_FK  foreign key (REG_USU_OBJETIVO)
                 references GEN_USUARIO (USU_CODIGO) on delete cascade
    )]');

  -- Bitacora: cada alerta disparada (tambien alimenta el feed de la pagina).
  ddl(q'[
    create table MON_ALERTA (
      ALE_CODIGO     number generated by default as identity primary key,
      ALE_REG_CODIGO number not null,
      ALE_USU_CODIGO number not null,
      ALE_TIPO       varchar2(12) not null,
      ALE_DETALLE    varchar2(300),
      ALE_LAT        number,
      ALE_LNG        number,
      ALE_VEL_KMH    number,
      ALE_FECHA      timestamp default systimestamp not null,
      ALE_VISTO      varchar2(1) default 'N' not null,
      constraint MON_ALERTA_REG_FK foreign key (ALE_REG_CODIGO)
                 references MON_REGLA (REG_CODIGO) on delete cascade,
      constraint MON_ALERTA_USU_FK foreign key (ALE_USU_CODIGO)
                 references GEN_USUARIO (USU_CODIGO) on delete cascade
    )]');
  ddl('create index MON_ALERTA_IX on MON_ALERTA (ALE_FECHA desc)');
end;
/
commit
/
