-- ============================================================================
--  Croquis y areas sobre mapas - tabla. Guarda geometrias como GeoJSON (CLOB).
--  Idempotente (atrapa "ya existe").
-- ============================================================================
declare
  procedure ddl(p varchar2) is
  begin execute immediate p;
  exception when others then if sqlcode not in (-955,-1430,-2260,-2261,-2264,-1442,-1451) then raise; end if; end;
begin
  ddl(q'~create table MAP_AREA (
    ARE_CODIGO      number generated by default as identity primary key,
    ARE_NOMBRE      varchar2(120) not null,
    ARE_DESCRIPCION varchar2(500),
    ARE_TIPO        varchar2(12) not null
                    constraint MAP_ARE_TIPO_CK check (ARE_TIPO in ('POLIGONO','LINEA','CIRCULO','RECTANGULO')),
    ARE_CATEGORIA   varchar2(80),
    ARE_COLOR       varchar2(9) default '#2563eb',
    ARE_GEOJSON     clob,               -- Feature GeoJSON (circulo = Point + properties.radius)
    ARE_AREA_M2     number,             -- superficie
    ARE_LONGITUD_M  number,             -- longitud (linea) o perimetro
    ARE_ACTIVO      varchar2(1) default 'S' not null,
    ARE_FECHA_CREA  timestamp default systimestamp,
    ARE_USUARIO_CREA varchar2(60)
  )~');
end;
/
