-- ============================================================================
--  Rutas y navegacion - tablas. Rutas con paradas ordenadas + geometria + tiempos.
--  Idempotente (atrapa "ya existe").
-- ============================================================================
declare
  procedure ddl(p varchar2) is
  begin execute immediate p;
  exception when others then if sqlcode not in (-955,-1430,-2260,-2261,-2264,-1442,-1451) then raise; end if; end;
begin
  ddl(q'~create table RUT_RUTA (
    RUT_CODIGO      number generated by default as identity primary key,
    RUT_NOMBRE      varchar2(120) not null,
    RUT_DESCRIPCION varchar2(500),
    RUT_DISTANCIA_M number,
    RUT_DURACION_S  number,
    RUT_GEOJSON     clob,
    RUT_ACTIVO      varchar2(1) default 'S' not null,
    RUT_FECHA_CREA  timestamp default systimestamp,
    RUT_USUARIO_CREA varchar2(60)
  )~');
  ddl(q'~create table RUT_PARADA (
    PAR_CODIGO     number generated by default as identity primary key,
    PAR_RUT_CODIGO number not null constraint RUT_PAR_FK references RUT_RUTA on delete cascade,
    PAR_ORDEN      number not null,
    PAR_NOMBRE     varchar2(160),
    PAR_LAT        number not null,
    PAR_LNG        number not null
  )~');
  ddl('create index RUT_PAR_IX on RUT_PARADA (PAR_RUT_CODIGO, PAR_ORDEN)');
end;
/
